# Generated by Django 4.0.3 on 2023-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('ref_produit', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('qte_stock', models.IntegerField()),
                ('marque', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
    ]
